import Footer from "@/components/ui/footer";
import "./css/style.css";

import { Inter } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">

      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <div className="">
          <div className=""></div>
        </div>
        <div className=" flex-col overflow-hidden supports-[overflow:clip]:overflow-clip h-full w-full dark:bg-dark bg-white  dark:bg-dot-black/[0.2] bg-grid-white/[0.2] relative flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
